### PR TITLE
feat: update valibot dependency to >=v0.33.0

### PR DESCRIPTION
**Pull request by fabian-hiller**
Unfortunately, I introduced a breaking change in a type of Valibot v0.33.0. So I updated the dependencies.

### CODE REVIEW

**Comment by songkeys** [comment]
Thank you!

**Comment by songkeys** [comment]
May I ask the breaking changes? According to the [changelog](https://github.com/fabian-hiller/valibot/releases/tag/v0.33.0), it doesn't affect this repo's compatibility, right?

**Comment by fabian-hiller** [comment]
This was a change in the `.path` property of the `BaseIssue` type. Due to this change, TypeScript throws an error when passing a schema written in >=v0.33.0 to the adapter.

**Comment by songkeys** [comment]
I'm still a bit confused. If there are no required changes in the code of this repository, can we say that the current version of this repo is compatible with both valibot versions >=v0.31.0 and also >=v0.33.0? In other words, no specific version change is necessary for this library?

**Comment by fabian-hiller** [comment]
Yes, no code change is required. Just a type change by upgrading to >=v0.33.0. This is because the schema passed must be of the type `BaseSchema` as specified [here](https://github.com/Songkeys/mantine-form-valibot-resolver/blob/main/src/valibot-resolver.ts#L12).

**Comment by songkeys** [comment]
I think I should revert this PR then? Because the current version will support valibot >=v0.31.0 (which includes >=v0.33.0).

**Comment by fabian-hiller** [comment]
I thought so too, but for Modular Forms this leads to TS errors. Feel free to try it yourself.

**Pull request merged**
